# Generated by Django 3.1.5 on 2021-01-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_viewer', '0002_auto_20210106_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('price', models.FloatField()),
                ('link', models.URLField(max_length=180)),
                ('date', models.DateTimeField()),
                ('num', models.BigIntegerField(unique=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SearchPhrases',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('phrase', models.CharField(max_length=180, unique=True)),
                ('ads', models.ManyToManyField(to='parser_viewer.Ad')),
            ],
            options={
                'ordering': ['phrase'],
            },
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
