# Generated by Django 3.1.5 on 2021-01-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_viewer', '0003_auto_20210106_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='num',
        ),
        migrations.AlterField(
            model_name='ad',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='searchphrases',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
