# Generated by Django 3.1.5 on 2021-01-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_viewer', '0004_auto_20210106_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchphrases',
            name='ads',
            field=models.ManyToManyField(blank=True, to='parser_viewer.Ad'),
        ),
    ]
